server: "hub-cloud.browserstack.com"
user: ""
key: ""

common_caps:
  "browserstack.debug": true
  "acceptSslCerts": true
  "browserstack.ie.enablePopups": true
  "browserstack.video": true
  "build": "capybara-browserstack"

browser_caps:
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "Chrome"
    "browser_version": "56.0"
    "resolution": "2048x1536"
