#!/bin/bash

if [ -s /usr/local/rvm/scripts/rvm ]; then
  source /usr/local/rvm/scripts/rvm
elif [ -s ~/.rvm/scripts/rvm ]; then
  source ~/.rvm/scripts/rvm
fi

rvm use ruby-2.3.3

bundle install || exit 1
spinach -r console
